import { useEffect, useState } from 'react';
import { BarChart3, CheckCircle, AlertTriangle } from 'lucide-react';
import { reportsApi } from '@/services/api';
import type { AuditReport } from '@/services/types';

export function Reports() {
  const [reports, setReports] = useState<AuditReport[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    reportsApi.list().then(setReports).finally(() => setLoading(false));
  }, []);

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-2xl font-bold text-gray-900 dark:text-gray-100">Reports</h2>
        <p className="text-sm text-gray-500 dark:text-gray-400">Weekly audits and checkpoints</p>
      </div>

      {loading ? (
        <div className="text-center text-sm text-gray-400">Loading...</div>
      ) : reports.length === 0 ? (
        <div className="text-center text-sm text-gray-400">
          No reports yet. Reports are generated by weekly audit jobs.
        </div>
      ) : (
        <div className="space-y-4">
          {reports.map((report) => (
            <div
              key={report.id}
              className="rounded-xl border bg-white p-5 shadow-sm dark:bg-gray-900 dark:border-gray-800"
            >
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="rounded-lg bg-indigo-50 p-2 dark:bg-indigo-500/10">
                    <BarChart3 size={16} className="text-indigo-600 dark:text-indigo-400" />
                  </div>
                  <div>
                    <p className="text-sm font-semibold text-gray-900 dark:text-gray-100">
                      {report.type.replace(/_/g, ' ')}
                    </p>
                    <p className="text-xs text-gray-500 dark:text-gray-400">
                      {report.period_start} — {report.period_end}
                    </p>
                  </div>
                </div>
                <span
                  className={`flex items-center gap-1 rounded-full px-2.5 py-0.5 text-xs font-medium ${
                    report.verdict === 'ALIGNED' || report.verdict === 'ON_TRACK'
                      ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-500/10 dark:text-emerald-400'
                      : 'bg-red-100 text-red-700 dark:bg-red-500/10 dark:text-red-400'
                  }`}
                >
                  {report.verdict === 'ALIGNED' || report.verdict === 'ON_TRACK' ? (
                    <CheckCircle size={12} />
                  ) : (
                    <AlertTriangle size={12} />
                  )}
                  {report.verdict}
                </span>
              </div>
              {report.payload && (
                <div className="mt-4 rounded-lg bg-gray-50 p-3 text-xs text-gray-600 dark:bg-gray-800 dark:text-gray-400">
                  <pre className="whitespace-pre-wrap overflow-auto max-h-40">
                    {JSON.stringify(report.payload, null, 2)}
                  </pre>
                </div>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
